### ISSUE TITLE
Not compatible with Quarkus: java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create

### ISSUE THREAD

**Issue by AbdallahAhmed** [meilisearch/meilisearch-java#579]
`Caused by: java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(byte[])'
	at com.meilisearch.sdk.http.CustomOkHttpClient.<clinit>(CustomOkHttpClient.java:20)
	at com.meilisearch.sdk.HttpClient.<init>(HttpClient.java:31)
	at com.meilisearch.sdk.Config.<init>(Config.java:77)
	at com.meilisearch.sdk.Config.<init>(Config.java:39)
	at com.meilisearch.sdk.Config.<init>(Config.java:29)`

Seems that OkHttp version used isn't compatible with Quarkus

**Comment by brunoocasali** [comment]
Hi @AbdallahAhmed which meilisearch-java and Java version are you using?

**Comment by AbdallahAhmed** [comment]
@brunoocasali meilisearch-java version 0.11.0 with Java 17

**Comment by brunoocasali** [comment]
Hi @AbdallahAhmed I did some digging into the code, and I couldn't find a reproduce the error. I sent more information here:

https://github.com/meilisearch/meilisearch-java/issues/585#issuecomment-1535480287

Can you check it and may help me reproduce the issue?

Thanks in advance!

**Comment by brunoocasali** [comment]
Hi @AbdallahAhmed, I still want to hear from you, but I'll close this issue because we just released [v0.11.1](https://github.com/meilisearch/meilisearch-java/releases/tag/v0.11.1) with do not allow the users to run the library without having the okhttp3. 
So your error is fixed there. :D

**Comment by ruapho** [comment]
Hi!
Actually, it is not fixed :-(
Seems like meilisearch needs a newer version of okhttp3 than quarkus. Here is an excerpt of my dependency tree:

```
+--- io.quarkus.platform:quarkus-bom:{strictly 3.6.3} -> 3.6.3
|    +--- com.squareup.okhttp3:okhttp:3.14.9 (c)
+--- com.meilisearch.sdk:meilisearch-java:0.11.5
|    \--- com.squareup.okhttp3:okhttp:[4.10.0,5.0.0) -> 3.14.9 (*)

(c) - A dependency constraint, not a dependency. The dependency affected by the constraint occurs elsewhere in the tree.
(*) - Indicates repeated occurrences of a transitive dependency subtree. Gradle expands transitive dependency subtrees only once per project; repeat occurrences only display the root of the subtree, followed by this annotation.
```

**Comment by brunoocasali** [comment]
That's a different issue @ruapho. The initial issue was that people were using meilisearch-java without providing an HTTP library, and now it is explicitly required.

Your issue could be solved if we loosen the requirements to allow older versions of okhttp. 
Can you or anyone else send a PR to fix that issue?
